// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef g_h
#define g_h
#include <FL/Fl.H>
double dist(double x1, double y_1, double x2, double y2);
double perimeter(int n, double x1[10000], double y_1[10000], double x2[10000], double y2[10000]);
double area(int n, double x1[10000], double y_1[10000], double x2[10000], double y2[10000]);
double diametr(int n, double x1[10000], double y_1[10000], double x2[10000], double y2[10000]);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Button.H>
extern Fl_Input *P;
extern Fl_Input *S;
extern Fl_Input *D;
#endif
